//Declare Arrays for the Graphics
var gfx = [];
var player = new Array();
var tower = new Array();

//Setup some global Varibles for needed
var scale = 3;
var debug = true;
var debugHigh = false;
var debugWindow;
var game;
var characterGfx = [null, null, null, null, null];
var characterImages = [];
var testDistance = 0;
var testDirection = 0;
var testPalette = 0;
var timerMaster = 0;
var timerMonsterMove = 0;
var timerMonsterAttack = 0;
var timerChampionStats = 0;
//var players = 0;
var towerSwitchesData = new Array();
var loadingInterval = 0;
var gfxUI = [];
var uiClickArea = [];
var redrawPlayerUiFlag = 0;

//Flags for determining whether some asycnhronous file calls were succesfully loaded (see fileloader.js "getFileData")
//When a file is called, we increase 'count'
//When a file is loaded, we increase 'max'
//When count == max (all is loaded), we increase 'done'
var dataLoaded = {
    count: 0,
    max: 0,
    done: 0
};
var gfxLoaded = {
    count: 0,
    max: 0,
    done: 0
};

//COLOURS AND PALETTES
var CLASS_SERP = 0,
    CLASS_DRAG = 1,
    CLASS_MOON = 2,
    CLASS_CHAOS = 3;

var PROFESSION_WARRIOR = 0,
    PROFESSION_WIZARD = 1,
    PROFESSION_ADVENTURER = 2,
    PROFESSION_CUTPURSE = 3;

var COLOUR_BLACK = 0,
    COLOUR_GREY_DARKEST = 1,
    COLOUR_GREY_DARK = 2,
    COLOUR_GREY_MEDIUM = 3,
    COLOUR_GREY_LIGHT = 4,
    COLOUR_GREEN_DARK = 5,
    COLOUR_GREEN = 6,
    COLOUR_BLUE_DARK = 7,
    COLOUR_BLUE = 8,
    COLOUR_RED_DARK = 9,
    COLOUR_BROWN = 10,
    COLOUR_PINK = 11,
    COLOUR_RED = 12,
    COLOUR_YELLOW = 13,
    COLOUR_WHITE = 14,
    COLOUR_TRANSPARENT = 15;

var COLOUR = new Array();
COLOUR[COLOUR_BLACK] = [0, 0, 0, 255];
COLOUR[COLOUR_GREY_DARKEST] = [64, 64, 64, 255];
COLOUR[COLOUR_GREY_DARK] = [96, 96, 96, 255];
COLOUR[COLOUR_GREY_MEDIUM] = [128, 128, 128, 255];
COLOUR[COLOUR_GREY_LIGHT] = [160, 160, 160, 255];
COLOUR[COLOUR_GREEN_DARK] = [32, 144, 32, 255];
COLOUR[COLOUR_GREEN] = [16, 192, 16, 255];
COLOUR[COLOUR_BLUE_DARK] = [0, 0, 224, 255];
COLOUR[COLOUR_BLUE] = [64, 128, 224, 255];
COLOUR[COLOUR_RED_DARK] = [128, 32, 16, 255];
COLOUR[COLOUR_BROWN] = [176, 48, 16, 255];
COLOUR[COLOUR_PINK] = [224, 144, 96, 255];
COLOUR[COLOUR_RED] = [208, 0, 0, 255];
COLOUR[COLOUR_YELLOW] = [224, 192, 0, 255];
COLOUR[COLOUR_WHITE] = [224, 224, 224, 255];
COLOUR[COLOUR_TRANSPARENT] = [0, 0, 0, 0];

var COLOUR_PLAYER = new Array();
COLOUR_PLAYER[0] = [COLOUR[COLOUR_WHITE], COLOUR[COLOUR_BLUE], COLOUR[COLOUR_BLUE_DARK]];
COLOUR_PLAYER[1] = [COLOUR[COLOUR_WHITE], COLOUR[COLOUR_RED], COLOUR[COLOUR_RED_DARK]];

var CLASS_COLOUR_SERP = 0,
    CLASS_COLOUR_CHAOS = 1,
    CLASS_COLOUR_DRAG = 2,
    CLASS_COLOUR_MOON = 3;

var CLASS_COLOUR = new Array();
CLASS_COLOUR[CLASS_COLOUR_SERP] = COLOUR[COLOUR_GREEN],
CLASS_COLOUR[CLASS_COLOUR_CHAOS] = COLOUR[COLOUR_YELLOW],
CLASS_COLOUR[CLASS_COLOUR_DRAG] = COLOUR[COLOUR_RED],
CLASS_COLOUR[CLASS_COLOUR_MOON] = COLOUR[COLOUR_BLUE];

var COLOUR_DOOR_NORMAL = 0,
    COLOUR_DOOR_BRONZE = 1,
    COLOUR_DOOR_IRON = 2,
    COLOUR_DOOR_SERPENT = 3,
    COLOUR_DOOR_CHAOS = 4,
    COLOUR_DOOR_DRAGON = 5,
    COLOUR_DOOR_MOON = 6,
    COLOUR_DOOR_CHROMATIC = 7,
    COLOUR_DOOR_VOID = 8;

var COLOUR_DECO_BRONZE = 0,
    COLOUR_DECO_SERPENT = 1,
    COLOUR_DECO_DRAGON = 2,
    COLOUR_DECO_MOON = 3,
    COLOUR_DECO_CHAOS = 4,
    COLOUR_DECO_IRON = 5,
    COLOUR_DECO_BROWN = 6,
    COLOUR_DECO_TAN = 7;

var COLOUR_SWITCH_SERPENT = 0,
    COLOUR_SWITCH_CHAOS = 1,
    COLOUR_SWITCH_DRAGON = 2,
    COLOUR_SWITCH_MOON = 3,
    COLOUR_SWITCH_GREY = 4,
    COLOUR_SWITCH_BLUEISH = 5,
    COLOUR_SWITCH_BROWN = 6,
    COLOUR_SWITCH_TAN = 7,
    COLOUR_SWITCH_BLACK = 8;

var DIRECTION_NORTH = 0,
    DIRECTION_EAST = 1,
    DIRECTION_SOUTH = 2,
    DIRECTION_WEST = 3;

var CHAR_DISTANCE_VERY_CLOSE = 0,
    CHAR_DISTANCE_CLOSE = 1,
    CHAR_DISTANCE_MID = 2,
    CHAR_DISTANCE_FAR = 3,
    CHAR_DISTANCE_DISTANT = 4,
    CHAR_DISTANCE_VERY_DISTANT = 5;

var CHAR_FRONT_SOLO = -1,
    CHAR_FRONT_LEFT = 0,
    CHAR_FRONT_RIGHT = 1,
    CHAR_BACK_RIGHT = 2,
    CHAR_BACK_LEFT = 3;

var objectPalette = {};
objectPalette["switch"] = new Array();
objectPalette["switch"]["default"] = [COLOUR[COLOUR_RED], COLOUR[COLOUR_BLUE], COLOUR[COLOUR_GREY_LIGHT], null];
objectPalette["switch"]["default-off"] = [COLOUR[COLOUR_GREY_LIGHT], COLOUR[COLOUR_RED], null, COLOUR[COLOUR_BLUE]];
objectPalette["switch"][COLOUR_SWITCH_SERPENT] = [COLOUR[COLOUR_GREEN], COLOUR[COLOUR_GREEN_DARK], COLOUR[COLOUR_WHITE], COLOUR[COLOUR_BLACK]];
objectPalette["switch"][COLOUR_SWITCH_MOON] = [COLOUR[COLOUR_BLUE], COLOUR[COLOUR_BLUE_DARK], COLOUR[COLOUR_WHITE], COLOUR[COLOUR_BLACK]];
objectPalette["switch"][COLOUR_SWITCH_DRAGON] = [COLOUR[COLOUR_RED], COLOUR[COLOUR_RED_DARK], COLOUR[COLOUR_WHITE], COLOUR[COLOUR_BLACK]];
objectPalette["switch"][COLOUR_SWITCH_CHAOS] = [COLOUR[COLOUR_YELLOW], COLOUR[COLOUR_PINK], COLOUR[COLOUR_WHITE], COLOUR[COLOUR_BLACK]];
objectPalette["switch"][COLOUR_SWITCH_BLUEISH] = [COLOUR[COLOUR_BLUE], COLOUR[COLOUR_GREEN], COLOUR[COLOUR_WHITE], COLOUR[COLOUR_BLACK]];
objectPalette["switch"][COLOUR_SWITCH_BROWN] = [COLOUR[COLOUR_BROWN], COLOUR[COLOUR_RED_DARK], COLOUR[COLOUR_WHITE], COLOUR[COLOUR_BLACK]];
objectPalette["switch"][COLOUR_SWITCH_GREY] = [COLOUR[COLOUR_GREY_MEDIUM], COLOUR[COLOUR_GREY_DARK], COLOUR[COLOUR_WHITE], COLOUR[COLOUR_BLACK]];
objectPalette["switch"][COLOUR_SWITCH_TAN] = [COLOUR[COLOUR_PINK], COLOUR[COLOUR_BROWN], COLOUR[COLOUR_WHITE], COLOUR[COLOUR_BLACK]];
objectPalette["switch"][COLOUR_SWITCH_BLACK] = [COLOUR[COLOUR_BLACK], COLOUR[COLOUR_BLACK], COLOUR[COLOUR_BLACK], COLOUR[COLOUR_BLACK]];
objectPalette["deco"] = new Array();
objectPalette["deco"]["default"] = [COLOUR[COLOUR_RED], COLOUR[COLOUR_BLUE], COLOUR[COLOUR_GREY_LIGHT]];
objectPalette["deco"][COLOUR_DECO_BRONZE] = [COLOUR[COLOUR_PINK], COLOUR[COLOUR_BROWN], COLOUR[COLOUR_RED_DARK]];
objectPalette["deco"][COLOUR_DECO_SERPENT] = [COLOUR[COLOUR_YELLOW], COLOUR[COLOUR_GREEN], COLOUR[COLOUR_GREEN_DARK]];
objectPalette["deco"][COLOUR_DECO_DRAGON] = [COLOUR[COLOUR_PINK], COLOUR[COLOUR_RED], COLOUR[COLOUR_RED_DARK]];
objectPalette["deco"][COLOUR_DECO_MOON] = [COLOUR[COLOUR_GREY_LIGHT], COLOUR[COLOUR_BLUE], COLOUR[COLOUR_BLUE_DARK]];
objectPalette["deco"][COLOUR_DECO_CHAOS] = [COLOUR[COLOUR_WHITE], COLOUR[COLOUR_YELLOW], COLOUR[COLOUR_PINK]];
objectPalette["deco"][COLOUR_DECO_IRON] = [COLOUR[COLOUR_GREY_LIGHT], COLOUR[COLOUR_GREY_MEDIUM], COLOUR[COLOUR_GREY_DARK]];
objectPalette["deco"][COLOUR_DECO_BROWN] = [COLOUR[COLOUR_YELLOW], COLOUR[COLOUR_PINK], COLOUR[COLOUR_BROWN]];
objectPalette["deco"][COLOUR_DECO_TAN] = [COLOUR[COLOUR_YELLOW], COLOUR[COLOUR_PINK], COLOUR[COLOUR_RED_DARK]];
objectPalette["door"] = new Array();
objectPalette["door"]["default"] = COLOUR[COLOUR_BLUE];
objectPalette["door"][COLOUR_DOOR_NORMAL] = COLOUR[COLOUR_GREY_DARKEST];
objectPalette["door"][COLOUR_DOOR_BRONZE] = COLOUR[COLOUR_RED_DARK];
objectPalette["door"][COLOUR_DOOR_IRON] = COLOUR[COLOUR_GREY_LIGHT];
objectPalette["door"][COLOUR_DOOR_SERPENT] = COLOUR[COLOUR_GREEN];
objectPalette["door"][COLOUR_DOOR_CHAOS] = COLOUR[COLOUR_YELLOW];
objectPalette["door"][COLOUR_DOOR_DRAGON] = COLOUR[COLOUR_RED];
objectPalette["door"][COLOUR_DOOR_MOON] = COLOUR[COLOUR_BLUE];
objectPalette["door"][COLOUR_DOOR_CHROMATIC] = COLOUR[COLOUR_WHITE];
objectPalette["door"][COLOUR_DOOR_VOID] = COLOUR[COLOUR_BLACK];

//Towers
var TOWER_NAME = ["MOD0", "SERP", "MOON", "DRAGON", "CHAOS", "ZENDIK"];
var TOWER_MOD0 = 0,
    TOWER_SERPENT = 1,
    TOWER_MOON = 2,
    TOWER_DRAGON = 3,
    TOWER_CHAOS = 4,
    TOWER_ZENDIK = 5,
    TOWER_CHAMPIONS = 6; //dummy tower to store champions
var towerThis = TOWER_MOD0;

//Background gfx
var background = new Array();
background[0] = new Array(0, 0, 128, 76, 0, 0);
background[1] = new Array(128, 0, 128, 76, 0, 0);

//Touch Screen Stuff
var canvas_x;
var canvas_y;

//CHAMPIONS
var CHAMPION_MAX = 16;

var CHA_BLODWYN = 0,
    CHA_MURLOCK = 1,
    CHA_ELEANOR = 2,
    CHA_ROSANNE = 3,
    CHA_ASTROTH = 4,
    CHA_ZOTHEN = 5,
    CHA_BALDRICK = 6,
    CHA_ELFRIC = 7,
    CHA_SIR_EDWARD = 8,
    CHA_MEGRIM = 9,
    CHA_SETHRA = 10,
    CHA_MR_FLAY = 11,
    CHA_ULRICH = 12,
    CHA_ZASTAPH = 13,
    CHA_HENGIST = 14,
    CHA_THAI_CHANG = 15;

var championData = new Array();
var chamionPocketData = [];
var champion = new Array();

//MONSTERS AND CHARACTERS
var IMAGE_CHA_LEG = 0,
    IMAGE_CHA_TORSO = 1,
    IMAGE_CHA_HEAD = 2,
    IMAGE_CHA_ARM = 3,
    IMAGE_CHA_MINI = 4;

var PART_CHA_LEG = 0,
    PART_CHA_TORSO = 1,
    PART_CHA_ARM_LEFT = 2,
    PART_CHA_HEAD = 3,
    PART_CHA_MINI = 4,
    PART_CHA_ARM_RIGHT = 5,
    PART_CHA_ARM_LEFT_ATTACK = 6,
    PART_CHA_ARM_RIGHT_ATTACK = 7;

var IMAGE_CHA_DISTANCE_1 = 0,
    IMAGE_CHA_DISTANCE_2 = 1,
    IMAGE_CHA_DISTANCE_3 = 2,
    IMAGE_CHA_DISTANCE_4 = 3;

var NUMBER_OF_DISTANCES = 6,
    NUMBER_OF_HEADS = 18,
    NUMBER_OF_TORSOS = 6,
    NUMBER_OF_LEGS = 9,
    NUMBER_OF_ARMS = 3,
    NUMBER_OF_MINIS = 8;

var IMAGE_MON_TORSO = 0,
    IMAGE_MON_ARM = 1,
    IMAGE_MON_MINI = 2;

//Character body part types
var CHA_HEAD_ASTROTH = 1,
    CHA_HEAD_SETHRA = 3,
    CHA_HEAD_MR_FLAY = 5,
    CHA_HEAD_BALDRICK = 7,
    CHA_HEAD_ZENDIK = 9,
    CHA_HEAD_ZASTAPH = 11,
    CHA_HEAD_ROSANNE = 13,
    CHA_HEAD_BLODWYN = 15,
    CHA_HEAD_DEMON = 17,
    CHA_HEAD_ULRICH = 0,
    CHA_HEAD_SIR_EDWARD = 2,
    CHA_HEAD_THAI_CHANG = 4,
    CHA_HEAD_ELFRIC = 6,
    CHA_HEAD_HENGIST = 8,
    CHA_HEAD_ZOTHEN = 10,
    CHA_HEAD_MEGRIM = 12,
    CHA_HEAD_ELEANOR = 14,
    CHA_HEAD_MURLOCK = 16;

var CHA_TORSO_MALE_NAKED = 0,
    CHA_TORSO_MALE = 1,
    CHA_TORSO_MALE_CHAIN = 2,
    CHA_TORSO_SKELETON = 3,
    CHA_TORSO_FEMALE_NAKED = 4,
    CHA_TORSO_FEMALE = 5;

var CHA_ARM_MALE = 0,
    CHA_ARM_SKELETON = 1,
    CHA_ARM_FEMALE = 2;

var CHA_LEG_MALE = 0,
    CHA_LEG_MALE_CHAIN = 1,
    CHA_LEG_SKELETON = 2,
    CHA_LEG_FEMALE_NAKED = 3,
    CHA_LEG_DEMON = 4,
    CHA_LEG_FEMALE = 5,
    CHA_LEG_FEMALE_PLATE = 6,
    CHA_LEG_FEMALE_CHAIN = 7,
    CHA_LEG_FEMALE_LEATHER = 8;

var CHA_MINI_MALE = 0,
    CHA_MINI_MALE_NAKED = 1,
    CHA_MINI_SKELETON = 2,
    CHA_MINI_FEMALE_NAKED = 3,
    CHA_MINI_DEMON = 4,
    CHA_MINI_FEMALE = 5,
    CHA_MINI_FEMALE_PLATE = 6,
    CHA_MINI_FEMALE_CHAIN = 7;

var CHA_BODY = new Array();

var CHA_GENDER_MALE = 0,
    CHA_GENDER_FEMALE = 1;

var MON_FORM_VENDOR_1 = 21,
    MON_FORM_VENDOR_2 = 22,
    MON_FORM_SUMMON = 101,
    MON_FORM_BEHOLDER = 102,
    MON_FORM_ENTITY = 103,
    MON_FORM_CRAB = 104,
    MON_FORM_DRAGON = 105,
    MON_FORM_DRAGON_SMALL = 106,
    MON_FORM_BEHEMOTH = 107;

var PALETTE_SERPENT = new Array(COLOUR[COLOUR_GREY_LIGHT], COLOUR[COLOUR_WHITE], COLOUR[COLOUR_GREEN], COLOUR[COLOUR_GREEN_DARK]),
    PALETTE_CHAOS = new Array(COLOUR[COLOUR_GREY_LIGHT], COLOUR[COLOUR_WHITE], COLOUR[COLOUR_YELLOW], COLOUR[COLOUR_PINK]),
    PALETTE_DRAGON = new Array(COLOUR[COLOUR_GREY_LIGHT], COLOUR[COLOUR_YELLOW], COLOUR[COLOUR_PINK], COLOUR[COLOUR_RED]),
    PALETTE_MOON = new Array(COLOUR[COLOUR_GREY_LIGHT], COLOUR[COLOUR_WHITE], COLOUR[COLOUR_BLUE], COLOUR[COLOUR_BLUE_DARK]);
PALETTE_DEAD = new Array(COLOUR[COLOUR_BLACK], COLOUR[COLOUR_GREY_MEDIUM], COLOUR[COLOUR_GREY_DARK], COLOUR[COLOUR_GREY_DARKEST]);

var MON_PALETTE_DEFAULT = [COLOUR[COLOUR_BLACK], COLOUR[COLOUR_GREY_LIGHT], COLOUR[COLOUR_BLUE], COLOUR[COLOUR_RED]];
var SHIELD_PALETTE_DEFAULT = new Array([255, 0, 255, 255], COLOUR[COLOUR_RED], COLOUR[COLOUR_GREY_LIGHT], COLOUR[COLOUR_BLUE]);
var ITEM_PALETTE_DEFAULT = new Array(COLOUR[COLOUR_GREEN], COLOUR[COLOUR_RED], COLOUR[COLOUR_GREY_LIGHT], COLOUR[COLOUR_BLUE]);

var monsterPaletteData;
var monsterPaletteMetaData;
var monsterHeadsData;
var monsterBodiesData;
var monsterPalette = new Array();
var monsterBigPalette = new Array();

CHA_BODY[0] = {
    leg: CHA_LEG_FEMALE_NAKED,
    torso: CHA_TORSO_FEMALE_NAKED,
    arm: CHA_ARM_MALE,
    mini: CHA_MINI_FEMALE_NAKED
};
CHA_BODY[1] = {
    leg: CHA_LEG_SKELETON,
    torso: CHA_TORSO_SKELETON,
    arm: CHA_ARM_SKELETON,
    mini: CHA_MINI_SKELETON
};
CHA_BODY[2] = {
    leg: CHA_LEG_MALE,
    torso: CHA_TORSO_MALE_NAKED,
    arm: CHA_ARM_MALE,
    mini: CHA_MINI_MALE_NAKED
};
CHA_BODY[3] = {
    leg: CHA_LEG_MALE,
    torso: CHA_TORSO_MALE,
    arm: CHA_ARM_MALE,
    mini: CHA_MINI_MALE
};
CHA_BODY[4] = {
    leg: CHA_LEG_FEMALE,
    torso: CHA_TORSO_FEMALE,
    arm: CHA_ARM_FEMALE,
    mini: CHA_MINI_FEMALE
};
CHA_BODY[5] = {
    leg: CHA_LEG_MALE,
    torso: CHA_TORSO_MALE,
    arm: CHA_ARM_MALE,
    mini: CHA_MINI_MALE_NAKED
};
CHA_BODY[6] = {
    leg: CHA_LEG_FEMALE_PLATE,
    torso: CHA_TORSO_FEMALE,
    arm: CHA_ARM_FEMALE,
    mini: CHA_MINI_FEMALE_PLATE
};
CHA_BODY[7] = {
    leg: CHA_LEG_MALE_CHAIN,
    torso: CHA_TORSO_MALE_CHAIN,
    arm: CHA_ARM_MALE,
    mini: CHA_MINI_FEMALE_NAKED
};
CHA_BODY[8] = {
    leg: CHA_LEG_FEMALE_CHAIN,
    torso: CHA_TORSO_FEMALE,
    arm: CHA_ARM_FEMALE,
    mini: CHA_MINI_FEMALE_CHAIN
};
CHA_BODY[9] = {
    leg: CHA_LEG_MALE_CHAIN,
    torso: CHA_TORSO_MALE_CHAIN,
    arm: CHA_ARM_MALE,
    mini: CHA_MINI_MALE
};
CHA_BODY[10] = {
    leg: CHA_LEG_FEMALE_PLATE,
    torso: CHA_TORSO_FEMALE,
    arm: CHA_ARM_FEMALE,
    mini: CHA_MINI_FEMALE_PLATE
};
CHA_BODY[11] = {
    leg: CHA_LEG_MALE,
    torso: CHA_TORSO_MALE_CHAIN,
    arm: CHA_ARM_MALE,
    mini: CHA_MINI_MALE
};
CHA_BODY[12] = {
    leg: CHA_LEG_DEMON,
    torso: CHA_TORSO_MALE_NAKED,
    arm: CHA_ARM_MALE,
    mini: CHA_MINI_DEMON
};
CHA_BODY[13] = {
    leg: CHA_LEG_DEMON,
    torso: CHA_TORSO_MALE_CHAIN,
    arm: CHA_ARM_MALE,
    mini: CHA_MINI_DEMON
};

var monsterMax = new Array();
var monsterTeamIdMax = 0;
var monsterAttackSequence = 0;
var monster = new Array();

//Switches
var SWITCH_WALL_NONE = 0,
    SWITCH_WALL_REMOVE = 2,
    SWITCH_WALL_TOGGLE_STONE_WALL = 4,
    SWITCH_WALL_OPEN_VOID_DOOR = 6,
    SWITCH_WALL_ROTATE_STONE_WALL = 8,
    SWITCH_WALL_TOGGLE_PILLAR = 10,
    SWITCH_WALL_PLACE_PILLAR = 12,
    SWITCH_WALL_ROTATE_WOOD_WALLS = 14;

var SWITCH_FLOOR_NONE = 0,
    SWITCH_FLOOR_SPIN_180 = 2,
    SWITCH_FLOOR_SPIN_RANDOM = 4,
    SWITCH_FLOOR_OPEN_VOID_LOCK_DOOR = 6,
    SWITCH_FLOOR_VIVIFY_MACHINE_EXTERNAL = 8,
    SWITCH_FLOOR_VIVIFY_MACHINE_INTERNAL = 10,
    SWITCH_FLOOR_WOOD_DOOR_CLOSER_1 = 12,
    SWITCH_FLOOR_WOOD_DOOR_CLOSER_2 = 14,
    SWITCH_FLOOR_TRADER_DOOR = 16,
    SWITCH_FLOOR_TOWER_ENTRANCE_SIDE_PAD = 18, //(X/Y OF OPPOSITE PAD)
    SWITCH_FLOOR_TOWER_ENTRANCE = 20, // (CENTRAL PAD) 
    SWITCH_FLOOR_REMOVE = 22, // (X/Y) *
    SWITCH_FLOOR_CLOSE_VOID_LOCK_DOOR = 24, // (X/Y) *
    SWITCH_FLOOR_TOGGLE_PILLAR = 26, // (X/Y) *
    SWITCH_FLOOR_CREATE_SPINNER = 28, // (OR OTHER) (X/Y) *
    SWITCH_FLOOR_OPEN_CREATE_WALL_WITH_SWITCHES = 30, //? (X/Y) *
    SWITCH_FLOOR_CREATE_PAD = 32, // (F/X/Y) 
    SWITCH_FLOOR_MOVE_PILLAR_AT_PLAYER = 34, // X,Y TO PLAYER X-1,Y-1 (SPECIAL CASE) **
    SWITCH_FLOOR_CREATE_PILLAR = 36, // (X/Y) *
    SWITCH_FLOOR_KEEP_ENTRANCE_SIDEPAD = 38, // (X/Y OF OPPOSITE PAD)
    SWITCH_FLOOR_KEEP_ENTRANCE_CENTRAL_PAD = 40,
    SWITCH_FLOOR_FLASH_TELEPORT = 42, // (F/X/Y)
    SWITCH_FLOOR_ROTATE_STONE_WALL = 44, // (X/Y) *
    SWITCH_FLOOR_TOGGLE_WALL = 46, // (X/Y) *
    SWITCH_FLOOR_SPINNER = 48, // (UNKNOWN DIFFERENCE) (X/Y) *
    SWITCH_FLOOR_CLICK_TELEPORT = 50, // (F/X/Y)
    SWITCH_FLOOR_TOGGLE_GREEN_PAD = 52, // (X/Y) *
    SWITCH_FLOOR_ROTATE_WOOD_WALL_COUNTER_CLOCKWISE = 54, // (X/Y) *
    SWITCH_FLOOR_TOGGLE_HOLE = 56, // (X/Y) *
    SWITCH_FLOOR_GAME_COMPLETION_PAD = 58, // **
    SWITCH_FLOOR_REMOVE_PILLAR_OTHER_EVENT = 60; // (X/Y) **

var UI_GFX_POCKET_EMPTY = 0,
    UI_GFX_POCKET_COIN = 1,
    UI_GFX_POCKET_COMMON_KEY = 2,
    UI_GFX_POCKET_ARROW = 3,
    UI_GFX_POCKET_ELF_ARROW = 4,
    UI_GFX_POCKET_GEM_GREY = 5,
    UI_GFX_POCKET_GEM_SERPENT = 6,
    UI_GFX_POCKET_GEM_CHAOS = 7,
    UI_GFX_POCKET_GEM_DRAGON = 8,
    UI_GFX_POCKET_GEM_MOON = 9,
    UI_GFX_POCKET_RING = 10,
    UI_GFX_POCKET_POTION = 11,
    UI_GFX_POCKET_KEY = 12,
    UI_GFX_POCKET_STAFF = 13,
    UI_GFX_POCKET_WAND = 14,
    UI_GFX_POCKET_SHIELD_1 = 15,
    UI_GFX_POCKET_SHIELD_2 = 16,
    UI_GFX_POCKET_SHIELD_3 = 17,
    UI_GFX_POCKET_SHIELD_4 = 18,
    UI_GFX_POCKET_SHIELD_5 = 19,
    UI_GFX_POCKET_SHIELD_6 = 20,
    UI_GFX_POCKET_SHIELD_7 = 21,
    UI_GFX_POCKET_AMOUR_LEATHER = 22,
    UI_GFX_POCKET_AMOUR_CHAIN = 23,
    UI_GFX_POCKET_AMOUR_PLATE = 24,
    UI_GFX_POCKET_PERMIT = 25,
    UI_GFX_POCKET_HAND_LEFT_AMOUR = 26,
    UI_GFX_POCKET_HAND_RIGHT_AMOUR = 27,
    UI_GFX_POCKET_DAGGER = 28,
    UI_GFX_POCKET_RING_SHINNY = 29,
    UI_GFX_POCKET_SHORT_SWORD = 30,
    UI_GFX_POCKET_GEM_GREENISH = 31,
    UI_GFX_POCKET_GEM_BROWN = 32,
    UI_GFX_POCKET_GEM_TAN = 33,
    UI_GFX_POCKET_SWORD_1 = 34,
    UI_GFX_POCKET_SWORD_2 = 35,
    UI_GFX_POCKET_SWORD_3 = 36,
    UI_GFX_POCKET_SWORD_4 = 37,
    UI_GFX_POCKET_SWORD_5 = 38,
    UI_GFX_POCKET_AXE_1 = 39,
    UI_GFX_POCKET_AXE_2 = 40,
    UI_GFX_POCKET_AXE_3 = 41,
    UI_GFX_POCKET_AXE_4 = 42,
    UI_GFX_POCKET_BOW = 43,
    UI_GFX_POCKET_CROSS_BOW = 44,
    UI_GFX_POCKET_APPLE_1 = 45,
    UI_GFX_POCKET_APPLE_2 = 46,
    UI_GFX_POCKET_APPLE_3 = 47,
    UI_GFX_POCKET_BISCUIT_1 = 48,
    UI_GFX_POCKET_BISCUIT_2 = 49,
    UI_GFX_POCKET_BISCUIT_3 = 50,
    UI_GFX_POCKET_CHICKEN_1 = 51,
    UI_GFX_POCKET_CHICKEN_2 = 52,
    UI_GFX_POCKET_CHICKEN_3 = 53,
    UI_GFX_POCKET_NEGG = 54,
    UI_GFX_POCKET_WATER_1 = 55,
    UI_GFX_POCKET_WATER_2 = 56,
    UI_GFX_POCKET_WATER_3 = 57,
    UI_GFX_POCKET_BONES = 58,
    UI_GFX_ICON_SPELL_1 = 59,
    UI_GFX_ICON_SPELL_2 = 60,
    UI_GFX_ICON_SPELL_3 = 61,
    UI_GFX_ICON_SPELL_4 = 62,
    UI_GFX_ICON_SPELL_COMPASS_NORTH = 64,
    UI_GFX_ICON_SPELL_COMPASS_EAST = 65,
    UI_GFX_ICON_SPELL_COMPASS_SOUTH = 66,
    UI_GFX_ICON_SPELL_COMPASS_WEST = 67,
    UI_GFX_ICON_SPELL_LEVITATE = 68,
    UI_GFX_ICON_SPELL_5 = 69,
    UI_GFX_ICON_SPELL_6 = 70,
    UI_GFX_ICON_SPELL_7 = 71,
    UI_GFX_POCKET_GLOVE = 72,
    UI_GFX_POCKET_BLANK = 73,
    UI_GFX_POCKET_SLECTION = 74,
    UI_GFX_POCKET_SPADE = 75,
    UI_GFX_POCKET_CLUB = 76,
    UI_GFX_POCKET_HEART = 77,
    UI_GFX_POCKET_DIAMOND = 78,
    UI_GFX_ICON_SPELL_GREY = 79,
    UI_GFX_ICON_SPELL_SERPENT = 80,
    UI_GFX_ICON_SPELL_CHAOS = 81,
    UI_GFX_ICON_SPELL_DRAGON = 82,
    UI_GFX_ICON_SPELL_MOON = 83,
    UI_GFX_ICON_SPELL_BOOK_DRAGON_LEFT = 84,
    UI_GFX_ICON_SPELL_BOOK_LEFT = 85,
    UI_GFX_ICON_SPELL_BOOK_RIGHT = 86,
    UI_GFX_ICON_SPELL_BOOK_DRAGON_RIGHT = 87,
    UI_GFX_POCKET_EMPTY_LEFT_HAND = 88,
    UI_GFX_POCKET_EMPTY_RIGHT_HAND = 89,
    UI_GFX_POCKET_EMPTY_AMOUR = 90,
    UI_GFX_POCKET_EMPTY_LARGE_SHIELD = 91,
    UI_GFX_POCKET_EMPTY_SMALL_SHEILD = 92,
    UI_GFX_ICON_PAUSE = 93,
    UI_GFX_ICON_SAVE = 94,
    UI_GFX_ICON_SLEEP = 95,
    UI_GFX_ICON_BOOKOFSKULLS = 96,
    UI_GFX_ICON_UNKNOWN = 97,
    UI_GFX_ICON_POCKETS = 98,
    UI_GFX_ICON_OPENDOOR = 99,
    UI_GFX_ICON_BACK = 100,
    UI_GFX_ICON_SCROLL_UP = 101,
    UI_GFX_ICON_SCROLL_DOWN = 102,
    UI_GFX_ICON_SPELL_8 = 103,
    UI_GFX_ICON_SPELL_9 = 104,
    UI_GFX_ICON_SPELL_10 = 105,
    UI_GFX_ICON_SPELL_11 = 106,
    UI_GFX_ICON_SPELL_12 = 107,
    UI_GFX_ICON_SPELL_13 = 108,
    UI_GFX_ICON_SPELL_14 = 109,
    UI_GFX_ICON_SPELL_15 = 110,
    UI_GFX_ICON_SPELL_16 = 111,
    UI_GFX_ICON_SELECTED = 112,
    UI_GFX_SPELLBOOK = 113,
    UI_GFX_SPELLBOOK_TURNPAGE_1 = 114,
    UI_GFX_SPELLBOOK_TURNPAGE_2 = 115,
    UI_GFX_SPELLBOOK_TURNPAGE_3 = 116,
    UI_GFX_SPELLBOOK_TURNPAGE_4 = 117,
    UI_GFX_SHIELD = 118,
    UI_GFX_ICON_SPELLBOOK = 119,
    UI_GFX_ICON_SCROLL = 120,
    UI_GFX_ICON_ATTACK = 121,
    UI_GFX_CHAIN_VERT = 122,
    UI_GFX_STATSBOX = 123,
    UI_GFX_ICON_ARROWS_RED = 124,
    UI_GFX_ICON_ARROWS_BLUE = 125,
    UI_GFX_SHIELD_FILLED = 126,
    UI_GFX_CHAIN_LONG = 127,
    UI_GFX_CHARACTER_BOX = 128,
    UI_GFX_POCKETBOX = 129,
    UI_GFX_NAME_BLUE = 130,
    UI_GFX_NAME_RED = 131,
    UI_GFX_SHIELD_RED = 132,
    UI_GFX_SHIELD_BLUE = 133,
    UI_GFX_PORTRAITS = 134,
    UI_GFX_GRAY_BAR = 135,
    UI_GFX_SHIELD_CHARACTERS = 136,
    UI_GFX_SHIELD_TYPES = 137,
    UI_GFX_SHIELD_BOTTOM = 138,
    UI_GFX_SHIELD_TOP = 139,
    UI_GFX_SCRIPT = 140,
    UI_GFX_FAIRIES = 141;

var LEFT_PANEL_MODE_STATS = 0,
    LEFT_PANEL_MODE_COMMAND = 1;

var UI_RIGHT_PANEL_MAIN = 0,
    UI_RIGHT_PANEL_SPELLBOOK = 1,
    UI_RIGHT_PANEL_POCKETS = 2,
    UI_RIGHT_PANEL_STATS = 3;

var UI_CLICK_CHAMP1 = 0,
    UI_CLICK_STATS_BOX = 1,
    UI_CLICK_CHAMP2 = 2,
    UI_CLICK_CHAMP3 = 3,
    UI_CLICK_CHAMP4 = 4,
    UI_CLICK_VIEWPORT = 5,
    UI_CLICK_NAMETAG = 6,
    UI_CLICK_SPELLBOOK_ICON = 7,
    UI_CLICK_CHARACTER_STATS = 8,
    UI_CLICK_INTERACT = 9,
    UI_CLICK_OPEN_POCKETS = 10,
    UI_CLICK_ROTATE_LEFT = 11,
    UI_CLICK_MOVE_FORWARD = 12,
    UI_CLICK_ROTATE_RIGHT = 13,
    UI_CLICK_ATTACK = 14,
    UI_CLICK_MOVE_LEFT = 15,
    UI_CLICK_MOVE_BACKWARDS = 16,
    UI_CLICK_MOVE_RIGHT = 17,
    UI_CLICK_DEFEND = 18,
    UI_CLICK_POCKET_SLOT_1 = 19,
    UI_CLICK_POCKET_SLOT_2 = 20,
    UI_CLICK_POCKET_SLOT_3 = 21,
    UI_CLICK_POCKET_SLOT_4 = 22,
    UI_CLICK_POCKET_SLOT_5 = 23,
    UI_CLICK_POCKET_SLOT_6 = 24,
    UI_CLICK_POCKET_SLOT_7 = 25,
    UI_CLICK_POCKET_SLOT_8 = 26,
    UI_CLICK_POCKET_SLOT_9 = 27,
    UI_CLICK_POCKET_SLOT_10 = 28,
    UI_CLICK_POCKET_SLOT_11 = 29,
    UI_CLICK_POCKET_SLOT_12 = 30,
    UI_CLICK_POCKET_CHARACTER_0 = 31,
    UI_CLICK_POCKET_CHARACTER_1 = 32,
    UI_CLICK_POCKET_CHARACTER_2 = 33,
    UI_CLICK_POCKET_CHARACTER_3 = 34,
    UI_CLICK_POCKET_HAND = 35,
    UI_CLICK_POCKET_BACK = 36,
    UI_CLICK_PAUSE = 37,
    UI_CLICK_SAVE = 38,
    UI_CLICK_SLEEP = 39,
    UI_CLICK_BACK = 40,
    UI_CLICK_TOGGLEUP = 41,
    UI_CLICK_TOGGLEDOWN = 42;

var FONT_ALIGNMENT_LEFT = 0,
    FONT_ALIGNMENT_CENTER = 1,
    FONT_ALIGNMENT_RIGHT = 2;

var KEYPAD_4 = 100,
    KEYPAD_5 = 101,
    KEYPAD_6 = 102,
    KEYPAD_7 = 103,
    KEYPAD_8 = 104,
    KEYPAD_9 = 105,
    KEY_END = 96,
    KEYPAD_PLUS = 107,
    KEY_L = 76,
    KEY_T = 84,
    KEY_SPACEBAR = 32,
    KEY_G = 71,
    KEY_W = 87,
    KEY_S = 83,
    KEY_A = 65,
    KEY_D = 68,
    KEY_Q = 81,
    KEY_E = 69,
    KEY_R = 82,
    KEY_F = 70,
    KEY_5 = 53,
    KEY_6 = 54,
    KEY_7 = 55,
    KEY_8 = 56,
    KEY_9 = 57,
    KEY_0 = 48,
    KEY_MINUS = 189,
    KEY_PLUS = 187;

//items
var item = new Array();

var POCKET_LEFT_HAND = 0,
    POCKET_RIGHT_HAND = 1,
    POCKET_TORSO = 2,
    POCKET_SHIELD = 3,
    POCKET_SLOT_0 = 4,
    POCKET_SLOT_1 = 5,
    POCKET_SLOT_2 = 6,
    POCKET_SLOT_3 = 7,
    POCKET_SLOT_4 = 8,
    POCKET_SLOT_5 = 9,
    POCKET_SLOT_6 = 10,
    POCKET_SLOT_7 = 11,
    POCKET_SLOT_8 = 12,
    POCKET_AMOUNT_KEYS = 13,
    POCKET_AMOUNT_COINS = 12,
    POCKET_AMOUNT_ARROWS = 11,
    POCKET_AMOUNT_ELF_ARROWS = 14;

var ITEM_NONE = 0,
	ITEM_COIN = 1,
	ITEM_KEY = 2;

var ITEM_TYPE_EMPTY = 0,
    ITEM_TYPE_STACKABLE = 1,
    ITEM_TYPE_FOOD = 1,
    ITEM_TYPE_POTION = 2,
    ITEM_TYPE_ARMOUR = 3,
    ITEM_TYPE_SHIELD = 4,
    ITEM_TYPE_GLOVES = 5,
    ITEM_TYPE_WEAPON = 6,
    ITEM_TYPE_RIP = 7,
    ITEM_TYPE_KEY = 8,
    ITEM_TYPE_WAND = 9,
    ITEM_TYPE_BOW = 10,
    ITEM_TYPE_PERMIT = 11,
    ITEM_TYPE_CRYSTAL = 12,
    ITEM_TYPE_GEM = 13,
    ITEM_TYPE_RING = 14,
    ITEM_TYPE_BOOK = 15;
